extends: airbnb-base

env:
  node: true
  mocha: true

parserOptions:
  ecmaVersion: 2017
  sourceType: script

rules:
  'comma-dangle': ['error', 'never']
  'strict': ['error', 'global']
  'max-len': ['error', { code: 120 }]
  'semi': ['error', 'never']