language: node_js

node_js:
  - '10'
  - '8'

script:
  - npm run lint
  - npm run coverage

jobs:
  include:
    - stage: Update docs
      if: branch = master
      script: npm run docs
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: out
        target_branch: gh-pages
        keep_history: false
        committer_from_gh: true